import React from 'react';
import type {
  RouteProps,
  NavigateFunction,
  Location,
  RouteMatch,
  RouteObject,
} from 'react-router-dom';
import { HelmetData } from 'react-helmet';
import { Request, Response } from 'express';
import { Document as DefaultDoc } from './Document';

export interface CtxBase {
  req?: Request;
  res?: Response;
  navigate?: NavigateFunction;
  location?: Location;
  scrollToTop?: ScrollToTop;
}

export interface Ctx extends CtxBase {
  match: RouteMatch;
}

export interface CtxStatic<D = Record<string, any>> extends Ctx {
  data: D | null;
}

export interface AsyncComponent {
  getInitialProps: (props: Ctx) => any;
  getStaticInitialProps: (props: CtxStatic) => any;
  load?: () => Promise<React.ReactNode>;
  getChunkName: () => string | undefined;
}

export type AsyncRouteComponentType<Props> = React.ComponentType<Props> &
  AsyncComponent;

/**
 * this type handles the component type in the route config object
 * {
 *   path: "/",
 *   exact: true,
 *   component: ReactComponent <- AsyncRouteableComponent
 * }
 */
export type AsyncRouteableComponent<Props = any> =
  | React.ComponentType<Props>
  // After.js Page Component (getInitialProps and ...)
  | AsyncRouteComponentType<Props>
  | NonNullable<RouteProps['element']>;

export interface AsyncRouteComponentState {
  Component: AsyncRouteableComponent | null;
}

export interface AsyncRouteProps<Props = any> extends RouteObject {
  element: AsyncRouteableComponent<Props>;
  children?: AsyncRouteProps[];
}

export type IRouteProps<TInitialData = any> = {
  prefetch: (pathname: string) => void;
  location: Location;
} & TInitialData;

export type ScrollToTop = React.RefObject<boolean>;

// result of getInitialProps
export interface InitialData {}

export interface ServerAppState {
  afterData: AfterClientData;
  initialData: InitialData;
}

export interface AsyncMatchPath extends RouteMatch {
  route: AsyncRouteProps;
}

export interface InitialProps {
  match: AsyncMatchPath | null;
  data: InitialData;
}

export interface AfterClientData {
  scrollToTop: ScrollToTop;
  ssg?: boolean;
}

// <AfterData /> will send this object
export interface ServerAppState {
  afterData: AfterClientData;
  initialData: InitialData;
}

// result of the render()
export interface RenderResult {
  html: string;
  redirect: string;
  statusCode: number;
  data: InitialData;
}

// special result of getInitialProps
export interface RedirectWithStatusCode {
  statusCode?: number;
  redirectTo?: string;
}

// renderApp()
export interface AfterRenderAppOptions<T> {
  req: Request;
  res: Response;
  assets: Assets;
  routes: AsyncRouteProps[];
  document?: typeof DefaultDoc;
  chunks: Chunks;
  scrollToTop?: boolean;
  ssg?: boolean;
  customRenderer?: (
    element: React.ReactElement<T>
  ) => { html: string } | Promise<{ html: string }>;
}

// render()
export type AfterRenderOptions<T> = Omit<AfterRenderAppOptions<T>, 'ssg'>;

// renderStatic()
export type AfterRenderStaticOptions<T> = Omit<AfterRenderAppOptions<T>, 'ssg'>;

// Result of Document
export interface RenderPageResult {
  html: string;
  helmet: HelmetData;
}

// TransitionBehavior
export type TransitionBehavior = 'blocking' | 'instant';

// Document.js
export interface DocumentgetInitialProps<T = RenderPageResult> {
  req: Request;
  res: Response;
  helmet: HelmetData;
  assets: Assets;
  data: ServerAppState;
  renderPage: () => Promise<T>;
  match: AsyncMatchPath | null;
  scripts: string[];
  styles: string[];
  scrollToTop: ScrollToTop;
}

export type DocumentProps<T = RenderPageResult> = Omit<
  DocumentgetInitialProps<T>,
  'req' | 'res' | 'renderPage' | 'scrollToTop'
> &
  T;
export type AfterContext = DocumentProps;

// getAssets utility function
export interface GetAssetsParams {
  chunks: Chunks;
  route?: AsyncRouteProps;
}

// ES Module type
export type Module<P> =
  | {
      default?: P;
      [x: string]: any;
    }
  | {
      exports?: P;
      [x: string]: any;
    };

// assets.json that generated by razzle
export interface Assets {
  [name: string]: {
    [ext: string]: string;
  };
}

// chunks.json that generated by razzle
export interface Chunks {
  [key: string]: {
    css: string[];
    js: string[];
  };
}
